### ISSUE TITLE
ENH: Usage of list_files

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatMissions#42]
**Is your feature request related to a problem? Please describe.**
pysat currently requires a file to exist before it is loaded.  This presents an issue for pysatMissions, as data is created on the fly, and should be interoperable for any given year.  The pysat test instruments solve this by generating a list of daily files for a period of three years.  pysatMissions currently imports those routines, which presents a problem for defining missions outside that three-year period.

**Describe the solution you'd like**
This should be opened up so that plans for missions in the future and past can be generated from TLEs.  A simple way is to define the span of dates to encompass a wide range of dates.  This requires an update to the core package, but could be time-consuming if I literally have to generate thousands of fake files in a list.

**Describe alternatives you've considered**
- Rework the load routine here to add requested file to the file list.
- Use the cadence features to define yearly files for the instruments, cutting down on the list size
- a bypass feature for this package

**Additional context**

**Comment by rstoneback** [comment]
The easiest current solution is to auto-generate a list of files for more dates. A method could be added to the init method for pysat_testing*.py to automatically regenerate a new list of files up to today on each instantiation.

The cadence option doesn’t cut down to file list size, it’ll expand a few files into a years worth per original file.

To avoid pre-generating file lists we’d need a way to hook a generator into the files class lookup. I’d have to take a look into the code to see what that would entail. The key location is in _instrument where load invokes the files class to get the list of files for the user selected dates.

On Dec 18, 2020, at 12:50 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:



Is your feature request related to a problem? Please describe.
pysat currently requires a file to exist before it is loaded. This presents an issue for pysatMissions, as data is created on the fly, and should be interoperable for any given year. The pysat test instruments solve this by generating a list of daily files for a period of three years. pysatMissions currently imports those routines, which presents a problem for defining missions outside that three-year period.

Describe the solution you'd like
This should be opened up so that plans for missions in the future and past can be generated from TLEs. A simple way is to define the span of dates to encompass a wide range of dates. This requires an update to the core package, but could be time-consuming if I literally have to generate thousands of fake files in a list.

Describe alternatives you've considered

  *   Rework the load routine here to add requested file to the file list.
  *   Use the cadence features to define yearly files for the instruments, cutting down on the list size
  *   a bypass feature for this package

Additional context
Add any other context or screenshots about the feature request here.

**Comment by rstoneback** [comment]
I did some testing of the performance of pysat v3.0.0 generating about as many files as the year range in date time supports.

```
In [21]: %timeit test = pysat.Instrument('pysat', 'testing', file_date_range=pds.date_range(dt.datetime(1700, 1, 1), dt.datetime(2221, 1, 1)), update_files=True)                                                           
864 ms ± 16.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
This is on my laptop.

**Comment by rstoneback** [comment]
Experimental support for a `list_files_creator` was added in pull #637.
It is expected to return a filename based upon the supplied key, from ``__getitem__``
```
            # Return filename generated on demand
             out = self.list_files_creator(key)
```
Creator is called when someone does
```
inst.files[date]
``` 
or similar. Perhaps more importantly, if a user issues a load call then pysat will internally interface with `inst.files`.

**Comment by jklenzing** [comment]
Somehow missed this was merged into pysat already.  The functionality is there!
```
import datetime as dt
import pandas as pds
import pysat
sat = pysat.Instrument('missions', 'sgp4', file_date_range=pds.date_range(dt.datetime(2020, 1, 1), dt.datetime(2021, 1, 1)))
sat.files.files
```

**Comment by rstoneback** [comment]
Let me know if you run into any problems. 🐵
