### ISSUE TITLE
ENH: conversions for sgp4

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatMissions#56]
**Is your feature request related to a problem? Please describe.**
The sgp4 instrument currently only outputs ECI coords.  These need to be converted into lat / long / alt.

**Describe the solution you'd like**
Conversions should be available in astropy

**Describe alternatives you've considered**
other conversion packages may be available

**Additional context**

**Comment by aburrell** [comment]
Astropy is a big dependency.  Might be worth it in this case, but still...

**Comment by rstoneback** [comment]
@lkilcommons has a relevant package here, https://github.com/lkilcommons/geospacepy-lite but comes with a note.

`
It's in the 'astrodynamics2' module, the functions are eci2ecef and solar_position_approx. I'd beware of the other functions in that code though...the test coverage for that module isn't great, so I really don't know if they are right or not.
`

**Comment by rstoneback** [comment]
That note is from an old email, I checked the package and found it here:
https://github.com/lkilcommons/geospacepy-lite/blob/develop/geospacepy/terrestrial_spherical.py

**Comment by rstoneback** [comment]
There is a translation from ECI to ECEF in geospacepy-lite and OMMBV has functions to go from ECEF to geodetic and geocentric.

**Comment by lkilcommons** [comment]
Yes, the geospacepy-lite package has been significantly improved (v0.2 release, real docs, tests) since that old email. Do be aware though that the ECI to ECEF transform accuracy/precision is a function of which definition of solar position (mean sun, true of date sun, etc.). I use the NRL low-accuracy solar position, and also don't account for leap seconds, so if you need very high precision position you may need something else. Let me know if I can answer questions on this.

**Comment by lkilcommons** [comment]
Also pymap3d can do eci/ecef: https://github.com/geospace-code/pymap3d

**Comment by rstoneback** [comment]
Thanks @lkilcommons! My original intent with this code, back when it was part of pysat itself, was to support work to demonstrate that instruments met science objectives when a satellite-like object was flown through a modeled atmosphere. I don't need leap seconds for that or many other applications. Since pysat uses pandas and xarray, both of which use the pandas datetimeindex, we currently can't represent leap seconds anyway. +1 for consistency 🙈

**Comment by lkilcommons** [comment]
Okay, well geospacepy-lite can definitely do the full ECI to geodetic, at least to 0th order. I use the mean sun, and only handle the simple rotation from the ECI reference direction to prime meridian about the ECI z-axis. I ignore the movement of the earth's rotation axis, so it's a pretty rough transform. Astropy provides the 'real' transform accounting for the those secondary effects (also I just noticed pymap3d appears to use Astropy for that).

**Comment by jklenzing** [comment]
Thanks @lkilcommons.  I plan to pick this up sometime after CEDAR, so I will probably pick your brain about it then.

**Comment by jklenzing** [comment]
Closing with merge of #66
